services :
   postgresql:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: postgres
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: yeon
      POSTGRES_PASSWORD: didgksehd


   redis:
     container_name: redis
     image: "redis:alpine"
     env_file:
       - .env
     ports:
       - "6379:6379"
